# Generated by Django 3.0.8 on 2022-09-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220831_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_booth',
            field=models.BooleanField(default=False),
        ),
    ]
