# Generated by Django 3.0.8 on 2022-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220906_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_booth',
            field=models.BooleanField(default=False),
        ),
    ]
