# Generated by Django 4.1 on 2022-08-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='booth',
            name='college',
            field=models.CharField(choices=[('학관', '학관'), ('포스코관', '포스코관'), ('경영관', '경영관')], max_length=20),
        ),
    ]
