# Generated by Django 3.0.8 on 2022-08-28 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='booth.Booth'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
