# Generated by Django 4.1 on 2022-08-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_booth_number_alter_booth_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='college',
            field=models.CharField(choices=[('교육관', '교육관'), ('대강당', '대강당'), ('신세계관', '신세계관'), ('생활관', '생활관'), ('정문', '정문'), ('포스코관', '포스코관'), ('학문관', '학문관'), ('후윳길', '후윳길')], max_length=20),
        ),
    ]
