# Generated by Django 4.1 on 2022-08-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_alter_booth_id_alter_comment_id_alter_day_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='thumnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
