# Generated by Django 4.1 on 2022-08-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_alter_booth_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.AddField(
            model_name='booth',
            name='thumnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booth.booth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
