name: Django CICD

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.ENV }}" >> .env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
  continuous-deployment:

    runs-on: ubuntu-latest

    steps:
      - name: Clean temp directory
        run: |
          rm -rf *
          rsync -r $GITHUB_WORKSPACE . 
      
      - name: archive deploy 
        run: tar cvfz ./deploy.zip *
        
      # Step 1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Step 2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name festival-deploy \
            --deployment-group-name festival-deploy-group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=festival-bucket,bundleType=zip,key=archive/deploy.zip
