name: Django CICD

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create env file
      run: |
        touch .env
        echo "${{ secrets.ENV }}" >> .env
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Checks-out your repository under $GITHUB_WORKSPACE so your job can access it
    - name: checkout release
      uses: actions/checkout@v3

    # Runs a single command using the runners shell 
    - name: Clean temp directory
      run: |
        rm -rf *
        rsync -r $GITHUB_WORKSPACE . 
      
    - name: archive drcloud 
      run: tar cvfz ./drcloud.tar.gz *
       
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./drcloud.tar.gz s3://github-action-codedeploy-s3/archive/
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name githubaction-test
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name githubaction-test-group
        --s3-location bucket=github-action-codedeploy-s3,bundleType=tgz,key=archive/drcloud.tar.gz
